#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
AWS_CLI=$(command -v aws)

export AWS_CONFIG_FILE="$DIR/aws_config"
exec aws-vault exec "${AWS_PROFILE:-security}" -- "$AWS_CLI" "$@"

